import fnfSettlementFormModel from './fnfSettlementFormModel';
const {
  formField: {
    // firstName,
    // lastName,
    // address1,
    // city,
    // zipcode,
    // country,
    // useAddressForPaymentDetails,
    // nameOnCard,
    // cardNumber,
    // expiryDate,
    // cvv,

    dateOfResignation,
    reasonForLeaving,
    noticePeriodRequested,
    noticePeriodApproved,
    excessNoticePeriod,
    lastWorkingDate,
    resignationLetter,
    availableEncashTypeOne,
    availableEncashTypeTwo,
    availableEncashTypeThree,
    availableEncashTypeFour,
    EncashTypeOne,
    EncashTypeTwo,
    EncashTypeThree,
    EncashTypeFour,
    availableInNoticeTypeOne,
    availableInNoticeTypeTwo,
    availableInNoticeTypeThree,
    availableInNoticeTypeFour,
    returnedOne,
    returnedTwo,
    returnedThree,
    returnedFour,
    duesClearedOne,
    duesClearedTwo,
    duesClearedThree,
    duesClearedFour,
  }
} = fnfSettlementFormModel;

export default {
  // [firstName.name]: 'nikhil',
  // [lastName.name]: 'alakri',
  // [address1.name]: 'dhawd wd',
  // [city.name]: '',
  // [zipcode.name]: '32233',
  // [country.name]: '',
  // [useAddressForPaymentDetails.name]: false,
  // [nameOnCard.name]: 'ddawda',
  // [cardNumber.name]: '4111111111111',
  // [expiryDate.name]: '',
  // [cvv.name]: '322',

  [dateOfResignation.name]: '',
  [reasonForLeaving.name]: '',
  [noticePeriodRequested.name]: '',
  [noticePeriodApproved.name]: '',
  [excessNoticePeriod.name]: '',
  [lastWorkingDate.name]: '',
  [resignationLetter.name]: '',
  [availableEncashTypeOne.name]: false,
  [availableEncashTypeTwo.name]: false,
  [availableEncashTypeThree.name]: false,
  [availableEncashTypeFour.name]: false,
  [EncashTypeOne.name]: '',
  [EncashTypeTwo.name]: '',
  [EncashTypeThree.name]: '',
  [EncashTypeFour.name]: '',
  [availableInNoticeTypeOne.name]: false,
  [availableInNoticeTypeTwo.name]: false,
  [availableInNoticeTypeThree.name]: false,
  [availableInNoticeTypeFour.name]: false,
  [returnedOne.name] : false,
  [returnedTwo.name] : false,
  [returnedThree.name] : false,
  [returnedFour.name] : false,
  [duesClearedOne.name] : false,
  [duesClearedTwo.name] : false,
  [duesClearedThree.name] : false,
  [duesClearedFour.name] : false,
};
